# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'slaveui.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox, QDialog
from QLed import QLed

stylestatus = "QStatusBar{padding-left:8px;background:rgba(255,255,255,0.9);color:black;font-weight:bold;}"


class Ui_Slave(object):
    def setupUi(self, Slave):
        Slave.setObjectName("Slave")
        Slave.resize(600, 450)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Slave.sizePolicy().hasHeightForWidth())
        Slave.setSizePolicy(sizePolicy)
        Slave.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.gridLayout = QtWidgets.QGridLayout(Slave)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton = QtWidgets.QPushButton(Slave)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 2, 2, 1, 1)
        self.tinreg = QtWidgets.QTabWidget(Slave)
        self.tinreg.setObjectName("tinreg")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tcoils = QtWidgets.QTableWidget(self.tab)
        self.tcoils.setObjectName("tcoils")
        self.tcoils.setColumnCount(2)
        self.tcoils.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tcoils.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tcoils.setHorizontalHeaderItem(1, item)
        self.gridLayout_2.addWidget(self.tcoils, 0, 0, 1, 1)
        self.tinreg.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.tdinp = QtWidgets.QTableWidget(self.tab_2)
        self.tdinp.setObjectName("tdinp")
        self.tdinp.setColumnCount(2)
        self.tdinp.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tdinp.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tdinp.setHorizontalHeaderItem(1, item)
        self.gridLayout_3.addWidget(self.tdinp, 0, 0, 1, 1)
        self.tinreg.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tab_3)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.tableWidget = QtWidgets.QTableWidget(self.tab_3)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        self.gridLayout_4.addWidget(self.tableWidget, 0, 0, 1, 1)
        self.tinreg.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.tab_4)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.tholreg = QtWidgets.QTableWidget(self.tab_4)
        self.tholreg.setObjectName("tholreg")
        self.tholreg.setColumnCount(2)
        self.tholreg.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tholreg.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tholreg.setHorizontalHeaderItem(1, item)
        self.gridLayout_5.addWidget(self.tholreg, 0, 0, 1, 1)
        self.tinreg.addTab(self.tab_4, "")
        self.gridLayout.addWidget(self.tinreg, 2, 1, 1, 1)
        self.label_s = QtWidgets.QLabel(Slave)
        self.label_s.setObjectName("label_s")
        self.gridLayout.addWidget(self.label_s, 3, 1, 1, 1)
        self.statusbar = QtWidgets.QStatusBar(Slave)
        self.statusbar.setObjectName("listWidget")
        self.statusbar.setStyleSheet(stylestatus)
        self.led = QLed(Slave, onColour=QLed.Green, shape=QLed.Circle)
        self.led.setFixedSize(30, 30)
        self.led.value = False
        self.gridLayout.addWidget(self.led, 1, 2, 1, 1)
        self.gridLayout.addWidget(self.statusbar, 4, 1, 1, 1)

        self.retranslateUi(Slave)
        self.tinreg.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(Slave)
        self.pushButton.clicked.connect(self.show_info)

    def retranslateUi(self, Slave):
        _translate = QtCore.QCoreApplication.translate
        Slave.setWindowTitle(_translate("Slave", "Slave"))
        self.pushButton.setText(_translate("Slave", "Info"))
        item = self.tcoils.horizontalHeaderItem(0)
        item.setText(_translate("Slave", "address"))
        item = self.tcoils.horizontalHeaderItem(1)
        item.setText(_translate("Slave", "value"))
        self.tinreg.setTabText(self.tinreg.indexOf(self.tab), _translate("Slave", "Coils"))
        item = self.tdinp.horizontalHeaderItem(0)
        item.setText(_translate("Slave", "address"))
        item = self.tdinp.horizontalHeaderItem(1)
        item.setText(_translate("Slave", "value"))
        self.tinreg.setTabText(self.tinreg.indexOf(self.tab_2), _translate("Slave", "Discrete Inputs"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Slave", "address"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Slave", "value"))
        self.tinreg.setTabText(self.tinreg.indexOf(self.tab_3), _translate("Slave", "Input Registers"))
        item = self.tholreg.horizontalHeaderItem(0)
        item.setText(_translate("Slave", "address"))
        item = self.tholreg.horizontalHeaderItem(1)
        item.setText(_translate("Slave", "value"))
        self.tinreg.setTabText(self.tinreg.indexOf(self.tab_4), _translate("Slave", "Holding Registers"))
        self.label_s.setText(_translate("Slave", "Status:"))


    def print_status(self, msg):
        self.statusbar.showMessage(msg)

    def show_info(self):
        msg = QMessageBox()
        msg.setWindowTitle("Info")
        msg.setText("Proiect realizat de Ichim Ioana si Gafencu Gabriel")
        msg.setIcon(QMessageBox.Information)
        x = msg.exec_()

class  MainSlave(QDialog):
    def __init__(self):
        super(MainSlave,self).__init__()
        ui = Ui_Slave()
        ui.setupUi(self)
        self.show()

if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    ms=MainSlave()
    sys.exit(app.exec_())
